[package]
name = "wasm-tests"
version = "0.1.0"
authors = ["NikVolf <frol.rage@gmail.com>"]

[dependencies]
pwasm-std = { git = "https://github.com/nikvolf/pwasm-std" }
pwasm-abi = { git = "https://github.com/nikvolf/pwasm-abi" }
pwasm-abi-derive = { git = "https://github.com/nikvolf/pwasm-abi", path = "derive" }

pwasm-test = { git = "https://github.com/fckt/pwasm-test" }

[features]
std = ["pwasm-std/std", "pwasm-abi/std"]

[[bin]]
name = "token"
path = "src/token.rs"

[profile.release]
panic = "abort"
